var rule = {
  title: 'BT影视',
  host: 'https://www.btbtl.com/',
  url: '/type/fyclass/fypage/',
  searchUrl: '/search/**',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  class_parse: '.nav-menu-items&&li;a&&Text;a&&href;.*/(.*?)/',
  play_parse: true,
  lazy: "",
  limit: 6,
  double: true,
  推荐: '.module-list;.module-items&&.module-item;a&&title;img&&data-src;.video-class&&Text;a&&href',
  一级: '.module-items .module-item;a&&title;img&&data-src;.module-item-caption&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.tag-link&&Text',
    img: '.module-item-pic&&img&&data-src',
    desc: '.video-info-items:eq(3)&&Text;.tag-link:eq(2)&&Text;.tag-link:eq(1)&&Text;.video-info-items:eq(1)&&Text;.video-info-items:eq(0)&&Text',
    content: '.vod_content&&Text',
    tabs: '.module-tab-item',
    lists: '.module-player-list:eq(#id)&&a',
    tab_text: 'div--small&&Text',
  },
  搜索: '.module-item;a&&title;img&&data-src;.video-class&&Text;a&&href',
}