var rule = {
  title: 'LAN6影视',
  host: 'http://lan6.net/',
  class_name: '电影&电视剧&综艺&动漫&短剧',
  class_url: '1&2&3&5&7',
  searchUrl: '/search.html?wd=**',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/list/fyclass/-_-_-_-_-_fypage',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.shoutu-vodlist li;a&&title;.lazyload&&data-original;.text&&Text;a&&href',
  一级: '.shoutu-vodlist li;a&&title;.lazyload&&data-original;.text&&Text;a&&href',
  二级: {
    title: 'h1&&Text',
    img: '.lazyload&&data-original',
    desc: '.tag&&Text;.tag&&a:eq(4)&&Text;.tag&&a:eq(2)&&Text;.shoutu-media-bd&&p:eq(1)&&Text;.shoutu-media-bd&&p:eq(2)&&Text',
    content: '.desc&&Text',
    tabs: '.panel-hd h3',
    lists: '.shoutu-playlist:eq(#id) li',
  },
  搜索: '*',
  tab_remove:['播放记录 清空','关注公众号'],
}