var rule = {
    title: '刷剧网',
    host: 'https://www.shuajuw.com',
    url: '/Show/fyclass--------fypage---.html',
    searchUrl: '/Search/**----------fypage---.html',
    searchable: 2,
    quickSearch: 0,
    filterable: 1,
    filter: '',
    filter_url: '',
    filter_def: {},
    headers: {
        'User-Agent': 'MOBILE_UA',
    },
    timeout: 5000,
    class_parse: '.nav&&.nav_item;a&&Text;a&&href;/Type/(.*?)\.html',
    cate_exclude: '',
    play_parse: true,
    lazy: `js:input = {parse: 1, url: input, js: ''}`,
    double: true,
    推荐: '.swiper-wrapper;.c-dywUim;.title&&Text;img&&data-original;.c-hDImTG&&Text;a&&href;',
    一级: '.c-ffeBOn;p&&Text;img&&data-original;.c-hDImTG&&Text;a&&href',
    二级: {
        title: '.title&&Text;.info&&p:eq(2)&&Text',
        img: 'img&&data-original',
        desc: '.info&&p:eq(3)&&Text;.info&&p:eq(4)&&Text;;.info&&p:eq(1)&&Text;.info&&p&&Text',
        content: '.bottom-detail&&Text',
        tabs: '.hl-plays-from&&a',
        lists: '.hl-plays-list:eq(#id)&&li',
    },
    //搜索: '列表;标题;图片;描述;链接;详情',
    搜索: '*',
}
