var rule = {
  title: '华乐影院',
  host: 'https://huale.tv',
  class_name: '电影&电视剧&综艺&动漫',
  class_url: '1&2&3&4',
  searchUrl: '/vodsearch/page/fypage/wd/**.html',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/vodshow/fyclass/page/fypage.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.public-list-box;a&&title;.lazy&&data-src;.public-list-prb&&Text;a&&href',
  一级: '.public-list-bj a;a&&title;.lazy&&data-src;.public-list-prb&&Text;a&&href',
  二级: {
    title: '.slide-info-title&&Text;.slide-info:eq(2)--strong&&Text',
    img: '.lazy&&data-src',
    desc: '.slide-info-remarks&&Text;.slide-info-remarks:eq(1)&&Text;.slide-info-remarks:eq(2)&&Text;.slide-info:eq(1)--strong&&Text;.info-parameter&&ul&&li:eq(3)&&Text',
    content: '#height_limit&&Text',
    tabs: '.anthology.wow.fadeInUp.animated&&.swiper-wrapper&&a',
    tab_text: 'a--span&&Text',
    lists: '.anthology-list-box:eq(#id) li',
  },
  搜索: '*',
}