var rule = {
  title: '嘀哩',
  host: 'https://www.dlidl.com/',
  class_name: '电影&电视剧&综艺&动漫',
  class_url: 'dianshiju&dianying&zongyi&dongman',
  searchUrl: '/search/**.html',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/vodlist/fyclass_____.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.pic-list.two-show li;a&&title;.lazyload&&data-original;.text-center&&Text;a&&href',
  一级: '.video-list li;a&&title;.lazyload&&data-original;.text-center&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.vod-seat&&a&&Text',
    img: '.lazyload&&data-original',
    desc: '.vod-info&&Text;.vod-info&&p:eq(3)&&Text;.vod-info&&p:eq(6)&&Text;.vod-info&&p:eq(2)&&Text;.vod-info&&p:eq(1)&&Text',
    content: '.detail-info&&Text',
    tabs: '.vod-player&&li',
    tab_text: 'a--span&&Text',
    lists: '.player-list.clearfix:eq(#id) li',
  },
  搜索: '.main-left li;h3&&Text;.lazyload&&data-original;.text-center&&Text;a&&href',
}