var rule = {
    title: '孜然影视',
    host: 'https://www.zrys.top',
    url: '/index.php/vod/show/id/fyclass/page/fypage/',
    searchUrl: '/index.php/vod/search/page/fypage/wd/**/',
    searchable: 2,
    quickSearch: 0,
    filterable: 0,
    headers: {
        'User-Agent': 'PC_UA',
    },
    class_parse: '.nav li.nav-menu-item;a&&Text;a&&href;/.*/(\\d+)/',
    play_parse: true,
    lazy:muban.mxpro.lazy,
    limit: 6,
    double:true,
    推荐: '.module-items;.module-item;.module-item-pic a&&title;.module-item-pic img&&data-src;.module-item-text&&Text;.module-item-pic a&&href;.module-item-caption&&Text',
    double: true,
    一级: '.module-item;.module-item-pic a&&title;.module-item-pic img&&data-src;.module-item-text&&Text;.module-item-pic a&&href',
    二级: {
        title: 'h1&&Text;.video-info-aux a&&title',
        img: '.module-item-pic img&&data-src',
        desc: '.tag-link a&&Text;a.tag-link:eq(1)&&Text;a.tag-link:eq(2)&&Text;.video-info-actor:eq(1)&&Text;.video-info-actor:eq(0) a&&Text',
        content: '.vod_content--a&&Text',
        tabs: '.module-tab-item--small',
        lists: '.sort-item:eq(#id) a',
    },
    搜索: '.module-items .module-search-item;h3&&Text;.module-item-pic img&&data-src;a.video-serial&&Text;a.video-serial&&href',
}