var rule = {
    title: '影剧星球',
    host: 'https://jumov.com',
    url: '/vod/list/fypage/fyclass/0/0/0/0/0/0',
    searchUrl: '/public/auto/search1.html?keyword=**&page=fypage',
    searchable: 1,
    quickSearch: 1,
    filterable: 0,
    filter: '',
    filter_url: '',
    filter_def: {},
    headers: {
        'User-Agent': 'PC_UA',
    },
    timeout: 5000,
    class_parse: '.swiper-wrapper&&li;a&&Text;a&&href;/vod/1/(.*?)/0/0/0/0/0/0',
    cate_exclude: '',
    play_parse: true,
    lazy: `js:input = {parse: 1, url: input, js: ''}`,
    double: true,
    推荐: 'body&&.public-list-box;.public-list-bj;*;img&&data-src;.public-list-prb&&Text;a&&href',
    一级: '.public-list-box;img&&alt;img&&data-src;.public-list-prb&&Text;a&&href',
    二级: {
        title: 'h3&&Text;',
        img: '.mask-1&&data-src',
        desc: ';.slide-info-remarks&&Text;;.slide-info.hide:eq(2)&&Text;.slide-info.hide:eq(1)&&Text',
        content: '.text.cor3&&Text',
        tabs: '.anthology-tab a',
        lists: '.anthology-list-play:eq(#id)&&li',
        tab_text: 'body&&Text',
        list_text: 'body&&Text',
        list_url: 'a&&href'
    },
    搜索: '.public-list-box;.thumb-txt&&Text;img&&data-src;.public-list-prb&&Text;a&&href',
}