var rule = {
    类型: '影视',
    title: '影视大全',
    host: 'https://www.sdsrty.com',
    url: '/index.php/vod/show/id/fyclass/page/fypage.html',
    searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
    searchable: 2,
    quickSearch: 0,
    filterable: 1,
    filter: '',
    filter_url: '',
    filter_def: {},
    headers: {
        'User-Agent': 'MOBILE_UA',
    },
    timeout: 5000,
    class_parse: '.nav-list&&li:lt(7);a&&Text;a&&href;.*/(.*?).html',
    cate_exclude: '',
    play_parse: true,
    lazy: "js:input = {parse: 1, url: input, js: ''}",
    double: true,
    推荐: 'ul.lazy-load-list&&li;li;*;*;*;*',
    一级: 'ul.lazy-load-list&&li;a&&title;img&&data-original;.state&&Text;a&&href',
    二级: {
        title: 'img&&alt;.tags--label&&Text',
        img: 'img&&src',
        desc: '.episodes--label&&Text;.year--label&&Text;.country--label&&Text;.performer--label&&Text;.director--label&&Text',
        content: '.summary-con&&Text',
        tabs: '.nav.nav-tabs&&a',
        lists: '.episodes-list:eq(#id)&&a',
    },
    搜索: 'ul.search-list&&li;h5&&Text;*;.col-sm-9&&p:eq(-2)&&Text;*',
}