var rule = {
  title: '看片狂人',
  host: 'https://kpkuang.sbs',
  class_name: '电影&电视剧&综艺&动漫&短剧',
  class_url: '1&2&3&4&37',
  searchUrl: '/vodsearch/**----------fypage---.html',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/vodshow/fyclass--------fypage-----.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.fed-list-info .fed-list-item;.uk-label&&Text;a&&data-original;.uk-position-bottom&&Text;a&&href',
  一级: '.fed-list-info .fed-list-item;a&&title;a&&data-original;.uk-position-bottom&&Text;a&&href',
  二级: {
    title: '.uk-card-title&&Text;.slide-info:eq(2)--strong&&Text',
    img: '.cover-shadow-xs&&data-original',
    desc: '.uk-text-left&&li:eq(7)&&Text;.uk-text-left&&li:eq(5)&&Text;.uk-text-left&&li:eq(4)&&Text;.uk-text-left&&li:eq(0)&&Text;.uk-text-left&&li:eq(1)&&Text',
    content: '.uk-text-left&&li:eq(-1)&&Text',
    tabs: '.yunlist li',
    tab_text: 'a&&data-linename',
    lists: '.uk-switcher:eq(1)&&.fed-play-item:eq(#id)&&a[href*=/vodplay]',
    list_text: 'a--span&&Text',
  },
  搜索: '.fed-deta-images.fed-list-info.uk-card;a&&title;a&&data-original;.fed-text-white&&Text;*',
  tab_remove:['视频排序：正序','最新更新'],
}