var rule = {
  title:'胖虎小站',
  host:'https://www.panghuys.site/',
  class_name: '电影&剧集&综艺&动漫',
  class_url: '1&2&3&4',
  searchUrl:'/phsch/page/fypage/wd/**.html',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url:'/vodshow/fyclass/page/fypage.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '*',
  一级:'.row li;a&&title;.pic .lazyload&&data-original;.item-status.text-overflow&&Text;a&&href',
  二级:{
    title:'h3&&a&&Text',
    img:'.pic .lazyload&&data-original',
    desc:'.row&&Text;..col-sm-6:eq(3)&&TExt;.col-xs-12.col-sm-6:eq(1)&&TExt;',
    content:'.text.text-row&&Text',
    tabs:'.playlist-tab li',
    lists:'.ewave-playlist-content:eq(#id)&&li',
    tab_text:'body&&Text',
    list_text:'body&&Text',
    list_url:'a&&href',
    list_url_prefix: '',
  },
  搜索:'*',
}