var rule = {
  title: '葡萄影视',
  host: 'https://www.putaoys.com/',
  class_name: '电影&电视剧',
  class_url: 'dianying&dianshiju',
  searchUrl: '/search/**----------fypage---.html',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/vod/list/fyclass--------fypage---.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.img-list.picList li;a&&title;img&&src;.text&&Text;a&&href',
  一级:  '.grid-mode.show-list li;h5&&a&&Text;.lazy&&data-original;.mod_version&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.detail-title&&span&&Text',
    img: 'img&&src',
    desc: '.info fn-clear&&Text;.info-performer:eq(2)&&Text;.info fn-clear:eq(3)&&Text',
    content: '.juqing&&Text',
    tabs: '.m3u8yun',
    tab_text: 'span&&Text',
    lists: '.play-list:eq(#id) a',
  },
  搜索: '*',
}