var rule = {
    title: '追影TV',
    host: 'http://svip.zhuiying.cyou/',
    searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
    url: '/index.php/vod/type/id/fyclass/page/fypage.html',
    headers: {
        'User-Agent': 'MOBILE_UA',
    },
    timeout: 5000,
    class_parse: 'body&&.hl-smnav li;a&&Text;a&&href;.*/(\\d+).html',
    limit: 40,
    play_parse: true,
    lazy: '',
    推荐: '.hl-vod-list;li;a&&title;a&&data-original;.remarks&&Text;a&&href;.hl-item-sub&&Text',
    double: true,
    一级: '.hl-vod-list&&.hl-list-item;a&&title;a&&data-original;.remarks&&Text;a&&href',
    二级: {
        title: '.hl-col-xs-12:eq(1)--em&&Text;.hl-col-xs-12:eq(2)&&Text',
        img: '.hl-lazy&&data-original',
        desc: '.hl-col-xs-12:eq(11)--em&&Text;.hl-col-xs-12:eq(5)--em&&Text;.hl-col-xs-12:eq(6)--em&&Text;.hl-col-xs-12:eq(3)--em&&Text;.hl-col-xs-12:eq(4)--em&&Text',
        content: '.hl-content-text&&Text',
        tabs: '.hl-tabs&&a',
        lists: '.hl-plays-list:eq(#id)&&li',
    },
    搜索: '.hl-list-item;a&&title;a&&data-original;.remarks&&Text;a&&href;.hl-text-muted.hl-lc-2&&Text',
}