var rule = {
  title: '金牌影院',
  host: 'https://tapedistributor.com/',
  url: '/index.php/vod/type/id/fyclass/page/fypage.html',
  searchUrl: '/index.php/vod/search/page/frpage/wd/**.html',
  class_name: '电影&剧集&综艺&动漫',
  class_url: '1&2&3&4',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  double: true,
  推荐: '*',
  一级: 'ul.myui-vodlist.clearfix li;a&&title;a&&data-original;.pic_text&&Text;a&&href',
  二级: {
    title: 'h5&&Text;.content_detail:eq(1)&&li&&a:eq(2)&&Text',
    img: '.myui-vodlist__box&&a&&data-original',
    desc: '.content_detail:eq(1)&&li:eq(1)&&Text;.content_detail:eq(1)&&li&&a&&Text;.content_detail:eq(1)&&li&&a:eq(1)&&Text;.content_detail:eq(1)&&li:eq(2)&&Text;.content_detail:eq(1)&&li:eq(3)&&Text',
    content: '.content_desc&&span&&Text',
    tabs: '',
    lists: '.myui-content__list:eq(#id).sort-list&&li',
  },
  搜索: '*',
}