var rule = {
  title: '金牌影院',
    host: 'https://www.ghw9zwp5.com/',
    url: '/vod/show/id/fyclass/page/fypage',
    searchUrl: '/api/mw-movie/anonymous/video/searchByWordPageable?keyword=**&pageNum=fypage&pageSize=12&type=false',
    //searchUrl: '/api/mw-movie/anonymous/video/list?ageNum=1&pageSize=30&sort=1&sortBy=1&type1=1',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'PC_UA',
    Referer: 'https://www.ghw9zwp5.com',
  },
  class_name: '电影&电视剧&综艺&动漫',
  class_url: '1&2&3&4',
  limit: 6,
  play_parse: true,
  lazy: "js:\n        let url_id = input.split('/')[5];\n        let jishu_id = input.split('/')[7];\n        let t = new Date().getTime();\n        eval(getCryptoJS);\n        let signkey = 'id=' + url_id + '&nid=' + jishu_id + '&key=cb808529bae6b6be45ecfab29a4889bc&t=' + t;\n        let key = CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\n        let json_data = JSON.parse(request('https://www.ghw9zwp5.com/api/mw-movie/anonymous/video/episode/url?id=' + url_id + '&nid=' + jishu_id, {\n            headers: {\n                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',\n                'deviceid': '58a80c52-138c-48fd-8edb-138fd74d12c8',\n                'sign': key,\n                't': t\n            }\n        }));\n        let url = json_data.data;\n        log(url);\n        if (url) {\n            input = {parse: 0, url: url, header: rule.headers};\n        }\n\n    ",
  图片替换: "js:\n        // log(MY_URL);\n        let src = decodeURIComponent(input).split(',')[0].split(' ')[0];\n        input = urljoin(MY_URL, src) + '@Referer=https://obs.gduamoe.com/';\n    ",
  一级: '.movie-ul&&.CzPZP;.title&&Text;.card-img&&img&&srcset;.tag&&Text;.CzPZP a&&href',
    二级: {
      title: 'h1&&Text',
      img: '.detail__CardImg-sc-9404fc7f-2&&img&&src',
      tabs: '.player_name',
      lists: '.kZjMVJ:eq(#id)&&a',
    },
    搜索: '*',
}