var rule = {
  title: '黑狐影院',
  host: 'https://www.ruzhupai.com',
  class_name: '电影&电视剧&综艺&动漫',
  class_url: '1&12&35&29',
  searchUrl: '/search.php?searchword=**',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/gk/fyclass-fypage.html',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.recommend_bx ul li;a&&title;img&&src;;a&&href',
  一级: '.list.clearfix ul li;.li_text&&a&&Text;img&&src;;a&&href',
  二级: {
    title: '.detail_name&&Text',
    img: 'img&&src',
    desc: '.dl.clearfix&&Text;.dl.clearfix:eq(5)&&Text;.dl.clearfix:eq(4)&&Text;.dl.clearfix:eq(5)&&Text;.dl.clearfix:eq1)(2)&&Text',
    content: '.pcjq.mb_none&&Text',
    tabs: '.tabt3',
    tab_text: '',
    lists: '.list_1:eq(#id) li',
  },
  搜索: '*',
}