[
{"name":"雷蒙影视概念宣传片","url": "https://lem.clem7.repl.co/N3RD/JN/CRIMETVPV.txt"},
{"name":"雷蒙","url": "https://lem.clem7.repl.co/N3RD/JN/tv.txt"},
{"name":"全网聚合","url": "https://ghproxy.com/https://raw.githubusercontent.com/leosam1024/tvbox/main/live/tive.txt"},
{"name":"全球","url": "https://ghproxy.com/raw.githubusercontent.com/fanmingming/live/main/tv/m3u/global.m3u"},
{"name":"4K8K","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/IPTV.m3u"},
{"name":"百事通","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/bestv.m3u"},
{"name":"重庆有线","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/cqyx.m3u"},
{"name":"港台节目","url": "http://www.stream-link.org/stream-link.m3u"},
{"name":"爱尚","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/aishang.m3u"},
{"name":"歌华有线","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/ghyx.m3u"},
{"name":"YSLive","url": "https://agit.ai/Yoursmile7/TVBox/raw/branch/master/live.txt"},
{"name":"FMLive","url": "https://xhdwc.tk/tvlive.txt"},
{"name":"YY轮播","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/yylunbo.m3u"},
{"name":"APTV","url": "https://ghproxy.com/https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/aptv-playback.m3u"},
{"name":"itouch","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/itouch.m3u"},
{"name":"ChinaTV","url": "https://ghproxy.com/https://raw.githubusercontent.com/whpsky/iptv/main/chinatv.m3u"},
{"name":"搜集","url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u"},
{"name":"斗鱼一起看","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/douyuyqk.m3u"},
{"name":"斗鱼直播","url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/yu.m3u"},
{"name":"虎牙一起看","url": "https://ghproxy.com/https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/huyayqk.m3u"},
{"name":"虎牙直播","url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/ya.m3u"},
{"name":"ZHGIPTV","url": "https://ghproxy.com/https://raw.githubusercontent.com/zhanghongguang/zhanghongguang.github.io/main/myiptv.m3u"},
{"name":"ZHGPlaylist","url": "https://ghproxy.com/https://raw.githubusercontent.com/zhanghongguang/zhanghongguang.github.io/main/playlist.m3u"},
{"name":"电台","url": "https://ghproxy.com/https://raw.githubusercontent.com/goolguy007/radioer/main/TVradio"},
{"name":"FTYLive","url": "http://hz752.love:63/txt/ysbox.txt"}
]
